system:
  db-type: "mysql"
  addr: 8989
  disable-auto-migrate: false

mysql:
  host: "localhost"
  port: "3306"
  username: "root"
  password: "123456"
  db-name: "testdb"
  config: "charset=utf8mb4&parseTime=True&loc=Local"
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: "info"
  log-zap: false

zap:
  level: "info"
  format: "console"
  output-path: "log/starlive.log"
  rotate-by-date: true  # 是否开启按日期分割日志文件
  max-size: 100      # 单个日志文件最大大小(MB)
  max-backups: 3      # 保留的旧日志文件数量
  max-age: 28         # 保留日志文件的最大天数
  compress: true
  log-in-console: true

jwt:
  signing-method: "RS256"
  access-token-expire: 600
  refresh-token-expire: 86400
  # issuer 签发域名确保令牌的安全性
  issuer: "http://127.0.0.1"
  # secret-key用于HS256/HS384/HS512签名方法 32位长度
  secret-key: "12345678901234567890123456789012"
  # RSA密钥配置 (用于RS256/RS384/RS512)
  private-key-path: ""
  public-key-path: "./casdoor_public_key.pem"