system:
  db-type: "mysql"
  addr: 8989
  disable-auto-migrate: true

mysql:
  host: "localhost"
  port: "3306"
  username: "root"
  password: "123456"
  db-name: "testdb"
  config: "charset=utf8mb4&parseTime=True&loc=Local"
  max-idle-conns: 10
  max-open-conns: 100
  # silent: 不输出任何日志 error: 只输出错误日志 info: 输出错误和信息日志 debug: 输出所有日志
  log-mode: "error"
  # true 写入日志文件
  log-zap: false

zap:
  level: "info"
  format: "console"
  output-path: "log/starlive.log"
  rotate-by-date: true  # 是否开启按日期分割日志文件
  level-separation: true # 按级别分离日志文件（info.log, error.log等）
  max-size: 100      # 单个日志文件最大大小(MB)
  max-backups: 30      # 保留的旧日志文件数量
  max-age: 28         # 保留日志文件的最大天数
  compress: true
  log-in-console: true

jwt:
  signing-method: "HS512"
  # 单位分钟
  access-token-expire: 1
  refresh-token-expire: 86400
  # issuer 签发域名确保令牌的安全性
  issuer: "http://127.0.0.1"
  # secret-key用于HS256/HS384/HS512签名方法 32位随机字符串
  secret-key: "zCTp57w5JkhNAhjf0nRrMjYsRMAst1BC"
  # RSA密钥配置 (用于RS256/RS384/RS512)
  private-key-path: ""
  public-key-path: "./casdoor_public_key.pem"