system:
  db-type: "mysql"
  addr: 8988
  disable-auto-migrate: true

mysql:
  path: "localhost"
  port: "3306"
  username: "test"
  password: "123456"
  db-name: "tinode"
  config: "charset=utf8mb4&parseTime=True&loc=Local"
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: "info"
  log-zap: false

zap:
  level: "info"
  format: "console"
  output-path: "log/starlive.log"
  rotate-by-date: true
  max-size: 100
  max-backups: 3
  max-age: 28
  compress: true
  log-in-console: true

jwt:
  secret-key: "123456"
  signing-method: "RS256"
  access-token-expire: 600
  refresh-token-expire: 86400
  issuer: "http://127.0.0.1"
  private-key-path: ""
  public-key-path: "./casdoor_public_key.pem"